### ISSUE TITLE
Balanced Font Styles & Weights for Mozilla Firefox + Other Major Issue Requests

### ISSUE THREAD

**Issue by TheWolfBunny64** [vednoc/custom-fonts#22]
vednoc, my man! It's been a while! I'll have you know I've been doing pretty well so far! Your custom font style still rocks, especially with the Super Mario Bros. NES font! Now, I'll lay it down the line in this issue. 

Ever since I transitioned from Google Chrome to Mozilla Firefox this past July, I noticed that the font styles and weights whilst using your custom fonts style on Firefox were... um... how do I put this delicately without sugarcoating it? Unbalanced. I can notice that some assets whilst browsing on Mozilla Firefox were a little bit on the **bold** side rather than being normal, even with the base font weight set to 400, and base font style set to normal. In fact, I bet this is also a common error for Chrome users too. A photo is listed below regarding the issue that I'm talking about, chiefly certain assets on websites you go to.
![UI example](https://github.com/user-attachments/assets/57d967be-6e59-4566-8d2d-63b779f78beb)

There's also something major that I need to point out. When the custom fonts style is downloaded for Stylus on Firefox, it doesn't use the style's personalized base font in the settings as intended unlike Google Chrome. It only uses the default fonts found in the "Language and Appearance" section of the settings of the Firefox browser (even with "Super Mario Bros. NES" being put down in the settings of the custom fonts style), unless if I were to mess with the browser's settings, and change the serif font to "Super Mario Bros. NES". And that could be a bit of a problem for people who are trying to view the internet via Firefox with their custom font. That's the main core reason why the font style and weight settings aren't acting like normal on Firefox. So the Stylus extension in whole is probably going to have to be fixed for Firefox users as a means to tackle this issue.

One last thing I should mention. The custom fonts style should also ultimately apply to font assets found in the sans-serif section. Believe it or not, I've taken notice of this while I was visiting streaming sites for live TV such as Plex, Sling TV Freestream, and DIRECTV, chiefly regarding the closed captioning asset. Let me show you what I mean by this.
![UI Font 2](https://github.com/user-attachments/assets/b3d841a1-b112-468a-84c6-13eb17415297)

But you know what? That's okay! After all, there's nothing a little update can't fix, right? Do you think you can please sort out these situations with a new major update? I would be very appreciated if you were to take care of these issues when you get around to them, vednoc! 

If all else fails at the end of the day, you could ultimately make the custom fonts style its own separate extension for Mozilla Firefox users as a potential failsafe. Sounds good, don't it?

Just make sure to use my Super Mario Bros. NES font as a test subject for this new update, okay?
[Super Mario Bros. NES Font](https://thewolfbunny64.itch.io/super-mario-bros-nes)

**Comment by binarynoise** [comment]
> bold

The font is bold, so text in that font will look bold. But I can't seem to load the font as style so :shrug: 

> subtitles in the wrong font

can't reproduce
