### ISSUE TITLE
gmail compose

### ISSUE THREAD

**Issue by pihentagy** [vednoc/custom-fonts#3]
Gmail compose uses monospace font (when using a rich text editor)

**Comment by vednoc** [comment]
Looks like "CC" and "Subject" fields are using monospace font. Is that what needs to be fixed?

![image](https://user-images.githubusercontent.com/18245694/116310968-f6b0e880-a7aa-11eb-9c34-85fa71536379.png)

**Comment by pihentagy** [comment]
No, they do not carry style information. The problem is with the Message field. Since it is (or it can be) a rich text field, the actual font matters.
Btw what is your monospace font? Looks cool, have to try it out!

![image](https://user-images.githubusercontent.com/29916/116379556-68bd1800-a813-11eb-9feb-ad650524a77e.png)

**Comment by vednoc** [comment]
I'll exclude message box altogether. Never really used "rich" e-mails before, so this is new to me.

The monospace font I'm using is a [customized variant][1] of Iosevka slab serif. I have a GitHub Actions repository to build it, just not entirely finished yet. If you want it, I can ping you once that's done or just send you the font.

[1]: https://typeof.net/Iosevka/customizer
