### ISSUE TITLE
"Object Event" error

### ISSUE THREAD

**Issue by nathgit** [vednoc/custom-fonts#5]
Every time I try to set the font I get an "object event" error at the bottom of the popup. What's the problem? I chose Tahoma for the base font, & Consolas for the Mono font.

**Comment by vednoc** [comment]
I apologize for the late response. Does this error still occur? It might be a bug in old version of Stylus.

**Comment by vednoc** [comment]
I'm closing this for now. If the error still occurs, feel free to let me know.
