### ISSUE TITLE
All input elements get monospace (not just text inputs, even buttons)

### ISSUE THREAD

**Issue by pihentagy** [vednoc/custom-fonts#6]
For example in this page fragment the button titled "Rendben".

Is that intentional?

```
<div class="xt_panel"><table debug="ld(panel)" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td colspan="101"><h2><span class="xt_span">Sikeres tranzakció</span></h2></td></tr><tr><td width="300" nowrap=""><label class="" style="margin-bottom: 16px">SimplePay tranzakció azonosító:</label></td><td nowrap=""><div class="xt_field">193677510</div></td></tr></tbody></table><div class="hr"></div><div style="width:100%;" class="xt_button button-box">
                    <script type="text/javascript"><!--
                    "use strict";
                    
                    var gtm_list = [];
                //--></script>
                
                            <script type="text/javascript"><!--
                            "use strict";
                            
                            gtm_list.push({"variant":"Fizetve","price":1883,"category":"Számla","quantity":1,"name":"MVM Next - Földgáz","id":10250});
                                                    //--></script>
                        
                    <script type="text/javascript"><!--
                    "use strict";
                    
                    dataLayer.push({
                        "event": "Purchase",
                        "ecommerce": {
                            "purchase": {
                                "actionField": {
                                    "id": "39971881",
                                    "revenue": "1883"
                                },
                                "products": gtm_list
                            }
                        }
                    });
                //--></script>
                <input class="button " type="button" onclick="xt_button_click(this,'szamla_list_uj')" id="button_szamla_list_uj" name="button_szamla_list_uj" xt_button_align="left" href="szamla_list_uj" value="Rendben"></div></div>
```

**Comment by vednoc** [comment]
I apologize for the late response. This is certainly not intentional, but I'll need to think and test some workarounds. Using an input element disguised as a button, instead of a button element itself, kinda breaks my mind. 🤦🏻‍♂️

**Comment by pihentagy** [comment]
I cannot see a problem there, but maybe I miss something.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button

**Comment by vednoc** [comment]
It's considered a bad practice. Some related examples:

- https://www.htmhell.dev/8-anchor-tag-used-as-button/
- https://www.htmhell.dev/14-not-my-type/

**Comment by pihentagy** [comment]
`<input type="button">` is not `<a type="button">`

It seems that `<button>` is rather similar to a submit type button. But yes, you can put any valid HTML inside the button element.

https://stackoverflow.com/questions/469059/button-vs-input-type-button-which-to-use

**Comment by vednoc** [comment]
I apologize for the confusion. Those examples were meant to illustrate a similar problem with other elements because I couldn't find this specific use-case on that website (but I might contribute it). Regardless, HTML has evolved a lot over the years and became (too) flexible/complex because of backwards compatibility. I've been paying more attention to good/bad practices in the last few years and there's plenty of bad practices pretty much everywhere.
