### ISSUE TITLE
Font Styles and Font Weights?

### ISSUE THREAD

**Issue by TheWolfBunny64** [vednoc/custom-fonts#7]
Is it possible to add in forced font styles (Normal, Italic, and Oblique) and forced font weights (Bold, Bolder. and Light) to the Custom Fonts style? Just asking! Thanks!

**Comment by vednoc** [comment]
Comic Sans/Mono FTW!
![image](https://user-images.githubusercontent.com/18245694/197629733-390961dc-40c7-425b-9e4a-2cf3c3d4c320.png)
