### ISSUE TITLE
Icons not showing correctly

### ISSUE THREAD

**Issue by notDavid** [vednoc/custom-fonts#8]
Hi there, thank you for the script it's really useful;

I often see icons not displaying correctly, like `Font-awesome` and such. Disabling the script fixes it.
Any chance you could fix that?

Here's an example:

`https://app.simplelogin.io/static/node_modules/font-awesome/css/font-awesome.css`

![220728-214821 firefox - 16](https://user-images.githubusercontent.com/1530401/181624782-147b28e3-6209-46a7-b58e-5d8d74367259.png)

**Comment by CharliePearce** [comment]
This is due to how FontAwesome changed their class selectors in v6.

On the off chance that you're still looking - I've submitted a pull request (#9) for a fix for sites making use of FontAwesome v6+.

**Comment by notDavid** [comment]
@CharliePearce That's great, thank you!

PS. did you miss a `'` at the end of [this](https://github.com/vednoc/custom-fonts/pull/9/files#diff-6907a1bc816695009d211910eab43502ff2160e2abf30fd6cde8193176cfc4b3R27) line ?

**Comment by CharliePearce** [comment]
Yes, yes I did - no idea how I didn't catch that one.

**Comment by vednoc** [comment]
I apologize for not seeing this issue earlier. Thank you @CharliePearce for taking the time out of your day to fix it in #9.
